import { Html, useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'
import { useRef } from 'react'



const Sign = () => {
  
  const aviso = useRef()
  const letrero = useGLTF('/textures/cyberpunk_diner_sign_japanese.glb')

  return (
  <primitive 
  ref={aviso}
  object={letrero.scene}
  position={[-10,-5,-8]}
  scale={[0.91,1.05,0.2]}
  rotation-y={7.02}
  />
  )
}

export default Sign

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LukeMarsh201 (https://sketchfab.com/LukeMarsh201)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cyberpunk-diner-sign-japanese-6ffce0f168534501bdd9199847d57831
title: Cyberpunk Diner Sign (Japanese)
*/

// import React, { useRef } from "react";
// import { Html, useGLTF } from "@react-three/drei";
// import Hero from "../HeroSection/Hero";
// export function Sign(props) {
//   const { nodes, materials } = useGLTF("/textures/cyberpunk_diner_sign_japanese.glb");
//   return (
//     <group {...props} dispose={null}>
//       <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
//         <mesh
//           name="Object_2"
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_2.geometry}
//           material={materials.Bar1}
//         />
//         <mesh
//           name="Object_3"
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_3.geometry}
//           material={materials.Bar_2}
//         />
//         <mesh
//           name="Object_5"
//           castShadow
//           receiveShadow
//           // geometry={nodes.Object_5.geometry}
//           // material={materials.Writing}
//         />
//         <mesh
//           name="Object_6"
//           castShadow
//           receiveShadow
//           // geometry={nodes.Object_6.geometry}
//           // material={materials.Writing}
//         >
//           <Html
//           transform
//           occlude
//           // center
//           position={[-2,-1,9]}
//           rotation-x={1.7}
//           // style={{
//           //   width: '1030px',
//           //   height: '800px'
//           // }}
//           >
//             <Hero />
//           </Html>
//         </mesh>
//         <mesh
//           name="Object_4"
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_4.geometry}
//           material={materials.Sign}
//         />
          
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/cyberpunk_diner_sign_japanese.glb");

